In [60]:
import pandas as pd

data = pd.read_csv("1976-2020-president.csv")
data.head()

,year,state,state_po,state_fips,state_cen,state_ic,office,candidate,party_detailed,writein,candidatevotes,totalvotes,version,notes,party_simplified
0,1976,ALABAMA,AL,1,63,41,US PRESIDENT,"CARTER, JIMMY",DEMOCRAT,False,659170,1182850,20210113,NaN,DEMOCRAT
1,1976,ALABAMA,AL,1,63,41,US PRESIDENT,"FORD, GERALD",REPUBLICAN,False,504070,1182850,20210113,NaN,REPUBLICAN
2,1976,ALABAMA,AL,1,63,41,US PRESIDENT,"MADDOX, LESTER",AMERICAN INDEPENDENT PARTY,False,9198,1182850,20210113,NaN,OTHER
3,1976,ALABAMA,AL,1,63,41,US PRESIDENT,"BUBAR, BENJAMIN """"BEN""""",PROHIBITION,False,6669,1182850,20210113,NaN,OTHER
4,1976,ALABAMA,AL,1,63,41,US PRESIDENT,"HALL, GUS",COMMUNIST PARTY USE,False,1954,1182850,20210113,NaN,OTHER

In [61]:
data["rank"] = data.groupby(["year", "state"])["candidatevotes"].rank(ascending=False)
data = data[["year", "state", "candidate", "party_simplified", "candidatevotes", "rank"]]
data = data.sort_values(["state", "year", "rank"])
data

,year,state,candidate,party_simplified,candidatevotes,rank
0,1976,ALABAMA,"CARTER, JIMMY",DEMOCRAT,659170,1.0
1,1976,ALABAMA,"FORD, GERALD",REPUBLICAN,504070,2.0
2,1976,ALABAMA,"MADDOX, LESTER",OTHER,9198,3.0
3,1976,ALABAMA,"BUBAR, BENJAMIN """"BEN""""",OTHER,6669,4.0
4,1976,ALABAMA,"HALL, GUS",OTHER,1954,5.0
...,...,...,...,...,...,...
4282,2020,WYOMING,"JORGENSEN, JO",LIBERTARIAN,5768,3.0
4283,2020,WYOMING,"PIERCE, BROCK",OTHER,2208,4.0
4284,2020,WYOMING,NaN,OTHER,1739,5.0
4286,2020,WYOMING,UNDERVOTES,OTHER,1459,6.0
4285,2020,WYOMING,OVERVOTES,OTHER,279,7.0

In [62]:
data.to_csv("election-data.csv", index=False)

In [63]:
data = data[(data["state"] == "SOUTH CAROLINA") & (data["rank"] == 1)]
data["previous_winner_party"] = data["party_simplified"].shift(1)
data = data.dropna()
data[data["party_simplified"] != data["previous_winner_party"]]

/var/folders/gt/hp_y969x7hgchgtzlj0y7nhc0000gn/T/ipykernel_30652/750664708.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["previous_winner_party"] = data["party_simplified"].shift(1)

,year,state,candidate,party_simplified,candidatevotes,rank,previous_winner_party
618,1980,SOUTH CAROLINA,"REAGAN, RONALD",REPUBLICAN,439277,1.0,DEMOCRAT